export const RESPONSABILIDADES_LABELS: Record<string, string> = {
  '05': 'Impuesto sobre la renta — Régimen ordinario',
  '06': 'Ingresos y patrimonio',
  '07': 'Retención en la fuente a título de renta',
  '08': 'Retención en la fuente — impuesto de timbre',
  '09': 'Retención en la fuente — impuesto sobre las ventas',
  '10': 'Usuario aduanero',
  '13': 'Gran contribuyente',
  '14': 'Informante de exógena',
  '15': 'Autorretenedor',
  '16': 'Obligación de facturar — filiales y subsidiarias',
  '22': 'Obligado aduanero',
  '24': 'Declarante del impuesto de patrimonio',
  '26': 'Régimen simple (uso histórico)',
  '32': 'Impuesto a la riqueza',
  '33': 'Impuesto nacional al consumo',
  '34': 'Impuesto nacional a la gasolina y ACPM',
  '35': 'Impuesto al carbono',
  '38': 'Monotributo',
  '42': 'Obligado a llevar contabilidad',
  '43': 'Período gravable especial',
  '45': 'No responsable de IVA (persona natural bajo tope)',
  '47': 'Régimen simple de tributación — RST',
  '48': 'Responsable del impuesto sobre las ventas — IVA',
  '49': 'No responsable del impuesto al consumo',
  '52': 'Facturador electrónico',
  '53': 'No obligado a facturar electrónicamente',
  '54': 'Impuesto al patrimonio — Ley 2010',
  '55': 'Impuesto a los dividendos',
}

export const CIIU_LABELS: Record<string, string> = {
  '0111': 'Cultivo de cereales, legumbres y semillas oleaginosas',
  '0121': 'Cultivo de frutas tropicales y subtropicales',
  '0122': 'Cultivo de plátano y banano',
  '0141': 'Cría de ganado bovino y bufalino',
  '0311': 'Pesca marítima',
  '0312': 'Pesca de agua dulce',
  '0321': 'Acuicultura marítima',
  '0322': 'Acuicultura de agua dulce',
  '1011': 'Procesamiento y conservación de carne y productos cárnicos',
  '1012': 'Procesamiento y conservación de pescado',
  '1020': 'Procesamiento y conservación de frutas, legumbres y hortalizas',
  '1040': 'Elaboración de productos lácteos',
  '1062': 'Descafeinado, tostión y molienda del café',
  '1081': 'Elaboración de productos de panadería',
  '1082': 'Elaboración de cacao, chocolate y confitería',
  '1089': 'Elaboración de otros productos alimenticios n.c.p.',
  '1101': 'Destilación, rectificación y mezcla de bebidas alcohólicas',
  '1102': 'Elaboración de bebidas fermentadas no destiladas',
  '1103': 'Producción de malta, cervezas y bebidas malteadas',
  '1104': 'Elaboración de bebidas no alcohólicas y aguas minerales',
  '4631': 'Comercio al por mayor de productos alimenticios',
  '4632': 'Comercio al por mayor de bebidas y tabaco',
  '4633': 'Comercio al por mayor de productos lácteos, huevos, aceites y grasas',
  '4690': 'Comercio al por mayor no especializado',
  '4711': 'Comercio al por menor — establecimientos con alimentos y bebidas',
  '4722': 'Comercio al por menor de lácteos y huevos',
  '4723': 'Comercio al por menor de carnes y productos cárnicos',
  '4724': 'Comercio al por menor de bebidas y tabaco',
  '4729': 'Comercio al por menor de otros productos alimenticios n.c.p.',
  '4773': 'Comercio al por menor de ferretería, pinturas y vidrio',
  '4799': 'Otros tipos de comercio al por menor no realizado en establecimientos',
  '4921': 'Transporte de pasajeros — servicio urbano',
  '4922': 'Transporte de pasajeros — servicio intermunicipal',
  '4923': 'Transporte de carga por carretera',
  '5011': 'Transporte marítimo y de cabotaje de pasajeros',
  '5012': 'Transporte marítimo y de cabotaje de carga',
  '5021': 'Transporte fluvial de pasajeros',
  '5022': 'Transporte fluvial de carga',
  '5111': 'Transporte aéreo nacional de pasajeros',
  '5112': 'Transporte aéreo internacional de pasajeros',
  '5120': 'Transporte aéreo de carga',
  '5210': 'Almacenamiento y depósito de mercancías',
  '5221': 'Servicios auxiliares para el transporte terrestre',
  '5222': 'Servicios de puertos y transporte acuático',
  '5223': 'Servicios de aeropuertos y navegación aérea',
  '5310': 'Actividades de correo',
  '5320': 'Actividades de mensajería',
  '5511': 'Alojamiento en hoteles',
  '5512': 'Alojamiento en apartahoteles',
  '5513': 'Alojamiento en centros vacacionales',
  '5514': 'Alojamiento rural',
  '5519': 'Otros tipos de alojamiento para visitantes',
  '5590': 'Otros tipos de alojamiento n.c.p.',
  '5611': 'Expendio a la mesa de comidas preparadas',
  '5612': 'Expendio por autoservicio de comidas preparadas',
  '5613': 'Expendio de comidas preparadas en cafeterías',
  '5619': 'Otros tipos de expendio de comidas preparadas n.c.p.',
  '5621': 'Catering para eventos',
  '5629': 'Otros servicios de comidas',
  '5630': 'Expendio de bebidas alcohólicas para consumo en el establecimiento',
  '6110': 'Telecomunicaciones alámbricas',
  '6120': 'Telecomunicaciones inalámbricas',
  '6201': 'Desarrollo de sistemas informáticos',
  '6202': 'Consultoría informática',
  '6311': 'Procesamiento de datos y hosting',
  '6412': 'Bancos comerciales',
  '6499': 'Otras actividades de servicio financiero n.c.p.',
  '6511': 'Seguros de vida',
  '6512': 'Seguros generales',
  '6810': 'Actividades inmobiliarias con bienes propios o arrendados',
  '6820': 'Actividades inmobiliarias a cambio de retribución',
  '6910': 'Actividades jurídicas',
  '6920': 'Contabilidad, auditoría y asesoría tributaria',
  '7010': 'Administración empresarial',
  '7020': 'Consultoría de gestión empresarial',
  '7110': 'Arquitectura e ingeniería',
  '7120': 'Ensayos y análisis técnicos',
  '7310': 'Publicidad',
  '7320': 'Estudios de mercado y encuestas de opinión',
  '7410': 'Actividades especializadas de diseño',
  '7420': 'Fotografía',
  '7490': 'Otras actividades profesionales, científicas y técnicas n.c.p.',
  '7711': 'Alquiler y arrendamiento de vehículos automotores',
  '7810': 'Empresas de empleos temporales',
  '7820': 'Empresas de servicios temporales',
  '7830': 'Suministro de talento humano permanente',
  '8010': 'Seguridad privada',
  '8020': 'Servicios de sistemas de seguridad',
  '8121': 'Limpieza general interior de edificios',
  '8122': 'Otras actividades de limpieza y mantenimiento de edificios',
  '8129': 'Otras actividades de limpieza',
  '8130': 'Paisajismo y mantenimiento de jardines',
  '8211': 'Servicios administrativos combinados de oficina',
  '8219': 'Fotocopiado, preparación de documentos y apoyo de oficina',
  '8220': 'Centros de llamadas',
  '8230': 'Organización de convenciones y eventos',
  '8299': 'Otros servicios de apoyo a las empresas n.c.p.',
  '9001': 'Creación literaria',
  '9002': 'Creación musical',
  '9004': 'Creación audiovisual',
  '9005': 'Artes plásticas y visuales',
  '9007': 'Espectáculos musicales en vivo',
  '9008': 'Otros espectáculos en vivo',
  '9200': 'Juegos de azar y apuestas',
  '9311': 'Gestión de instalaciones deportivas',
  '9319': 'Otras actividades deportivas',
  '9321': 'Parques de atracciones y parques temáticos',
  '9329': 'Otras actividades recreativas y de esparcimiento n.c.p.',
  '9601': 'Lavandería y limpieza en seco',
  '9602': 'Peluquería y tratamientos de belleza',
  '9609': 'Otras actividades de servicios personales n.c.p.',
}
